name: Gray Hair Developer
description: Fake it 'til you make it
meta_description: "Gray Hair Developer, Blogging about Programming"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: "/"
domain_name: 
google_analytics: 
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            
author:         'Wonjun Jang'
