# Dependencies
markdown:         kramdown
theme: jekyll-theme-architect
highlighter:      rouge

# Setup
title:            Onejune
tagline:          'June First'
description:      'Fake it 'til you make it'
url:              https://grayhairwonjun.github.io
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name: Wonjun Jang
  email:
  github: GrayhairWonjun
  twitter: wonjun62
  pinterest:
  linkedin: wjang62
  bio: Fake it 'til you make it
  email_md5: b79784fd653274c34fcc7ed848f4ce63

paginate:         10
paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
disqus: gray-hair-developer
google_analytics: UA-89750913-1
exclude: ["README.md"] # files to exclude

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
